### ISSUE TITLE
Implement a DiceRoll value type so that SimpleDice can also be a value type.

### ISSUE THREAD

**Issue by mrlegowatch** [mrlegowatch/RolePlayingCore#54]
SimpleDice is a class (reference type) in order to avoid polluting the Dice protocol with a mutable roll() function, that is immutable for most clients. SimpleDice is different because it needs to store intermediate rolls in an Int array, in order to describe them (roll description). For example, "3d4" might produce a roll description of "(3 + 1 + 5)".

I propose changing the roll() function to return a DiceRoll value type, that holds both the result and the roll description, so that the SimpleDice can be a value type.

Pros: 
- all Dice implementations are value types

Cons:
- the  roll description isn't often required by clients, so represents wasted string "computation"
- clients are now required to extract the result from the DiceRoll

**Comment by matt123miller** [comment]
I can look into this for you in a day or 2 😄

**Comment by mrlegowatch** [comment]
I have a branch labeled "DiceRoll" with a candidate solution, but if you want to give this a whirl, please do!
